### ISSUE TITLE
latest foreman and openscap fails on foreman-rake db:migrate

### ISSUE THREAD

**Issue by cristi1979** [theforeman/foreman_openscap#106]
Packages installed:
[root@puppet ~]# rpm -qa | grep -i "foreman\|openscap" | sort
foreman-1.8.1-1.el7.noarch
foreman-cli-1.8.1-1.el7.noarch
foreman-compute-1.8.1-1.el7.noarch
foreman-debug-1.8.0-1.el7.noarch
foreman-ec2-1.8.1-1.el7.noarch
foreman-gce-1.8.1-1.el7.noarch
foreman-libvirt-1.8.1-1.el7.noarch
foreman-ovirt-1.8.1-1.el7.noarch
foreman-postgresql-1.8.1-1.el7.noarch
foreman-proxy-1.8.1-1.el7.noarch
foreman-selinux-1.8.1-1.el7.noarch
foreman-vmware-1.8.1-1.el7.noarch
openscap-1.2.2-0.1.el7.centos.x86_64
ruby193-rubygem-foreman_abrt-0.0.6-1.el7.noarch
ruby193-rubygem-foreman_column_view-0.2.0-1.el7.noarch
ruby193-rubygem-foreman_docker-1.3.1-1.fm1_8.el7.noarch
ruby193-rubygem-foreman_hooks-0.3.7-3.el7.noarch
ruby193-rubygem-foreman_openscap-0.4.0-1.el7.noarch
ruby193-rubygem-foreman-tasks-0.6.12-2.el7.noarch
ruby193-rubygem-foreman_templates-1.5.0-1.el7.noarch
ruby193-rubygem-openscap-0.4.2-2.el7.noarch
ruby193-rubygem-puppetdb_foreman-0.1.2-1.el7.noarch
rubygem-hammer_cli_foreman-0.2.0-1.el7.noarch
rubygem-smart_proxy_openscap-0.4.0-1.el7.noarch

Error:
==  AddScaptimonyScapContentDigest: migrating =================================
-- add_column(:scaptimony_scap_contents, :digest, :string, {:limit=>128})
rake aborted!
An error has occurred, this and all later migrations canceled:

PGError: ERROR:  column "digest" of relation "scaptimony_scap_contents" already exists
: ALTER TABLE "scaptimony_scap_contents" ADD COLUMN "digest" character varying(128)

Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by cristi1979** [comment]
I removed /opt/rh/ruby193/root/usr/share/gems/gems/scaptimony-0.3.1/db/migrate/20150115155947_add_scaptimony_scap_content_digest.rb in order to skip this error

**Comment by ares** [comment]
It looks like you used database from different version of scaptimony that already had this column, is it reproducible on clean installation? Also this is migration comes from https://github.com/openscap/scaptimony so it would be great if you could report it there.

**Comment by cristi1979** [comment]
Doesn't happen with latest versions of openscap
